---
title: "Probability and Statistical Inference: Frequentist and Bayesian Perspectives"
author: "Ashley I Naimi"
date: "`r paste0('Spring ', 2024)`" #format(Sys.Date(), '%Y')
urlcolor: blue
bibliography: ref.bib
link-citations: yes
output: 
    bookdown::pdf_book:
      base_format: tint::tintPdf
      toc: true
      number_sections: true
      includes:
        in_header: ../../misc/preamble.tex
      latex_engine: xelatex
    html_document:
      theme: readable
      toc: true
      toc_float: true
      number_sections: true
      css: ../../misc/style.css
---

```{r setup, include=FALSE}
library(knitr)
library(formatR)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)

packages <- c( "data.table","tidyverse","ggplot2","ggExtra","formatR",
               "gridExtra","skimr","here","RColorBrewer","survival")

for (package in packages) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package, repos='http://lib.stat.cmu.edu/R/CRAN')
  }
}

for (package in packages) {
  library(package, character.only=T)
}

remotes::install_github("rstudio/fontawesome")

library(fontawesome)

thm <- theme_classic() +
  theme(
    legend.position = "top",
    legend.background = element_rect(fill = "transparent", colour = NA),
    legend.key = element_rect(fill = "transparent", colour = NA)
  )
theme_set(thm)
```

\newpage
\onehalfspacing

<!-- *There is considerable uncertainty about the study of uncertainty* -->

<!-- this chapter should be about the ways we (can) manage "uncertainty", how we've implicitly adopted one (flawed and) fallacious way, what some other options are ...  -->

<!-- Augustus de Morgan (1838): I consider the word probability as meaning the state of mind with respect to an assertion, a coming event, or any other matter on which absolute knowledge does not exist.  -->

<!-- John Venn freq defn of prob... -->

Much of what we are going to talk about in this course is related to, either directly or indirectly, the idea of **inference.** This word is used frequently in the sciences, so it might be useful to work on developing a more foundational understanding of what we mean by inference. There are many types or categories or classes of inference that we'll encounter as scientists: logical inferences, such as inductive, deductive, or abductive inferences, allow us to structure arguments and formally evaluate the validity of those structures; causal inferences, which enables us to combine data, models, and assumptions to quantify cause-effect relations; epidemiologic inferences, which involve using data, reason, logic, etc to understand how we can improve and/or protect population health; probabilistic inference, which allows us to map out a space of what's possible, and on the basis of this map, evaluate what's "likely"; and statistical inference, which allows us to assign measures of uncertainty or "error" to quantitative statements about the world. 

Note that these categories of inference are not at all mutually exclusive. Logic permeates all other forms of inference. Epidemiologic inference involves logical, probabilistic, statistical, and other forms of inference combined. They can and in many times are iteratively related and nested within each other: for example, probabilistic inference depends on logical inference, and statistical inference often relies on probability arguments. However, there is a common pattern characterizing each that we can abstract to better understand the process of inference: inference consists of taking several inputs and organizing them or transforming them in such a way that we get more than what went in. 

Inference: whole is more than sum of parts




<!-- "(...) "Black Swans" (Taleb, 2007). These cultural icons refer to disasters that occur so infrequently that they are virtually impossible to analyze using standard statistical inference. However, we find this perspective less than helpful because it suggests a state of hopeless ignorance in which we resign ourselves to being buffeted and battered by the unknowable." -->
<!-- Andrew Lo, who obviously did not bother to read the book he was citing. -->

<!-- a posture towards understanding reality:  -->

<!-- putting the "me" into episte-me: if i can't figure out the solution, then there isnt a problem! -->

<!-- The mistake appears to be commonly made in common inference about fat-tailed -->
<!-- data in the literature. The very methodology of using concentration and changes in concentration is highly questionable. For instance, in the thesis by Steven Pinker [212] that the world is becoming less violent, we note a fallacious inference about the concentration of damage from wars from a κbq with minutely small population in relation to the fat-tailedness.6 Owing to the fat-tailedness of war casualties and consequences of violent conflicts, an adjustment would rapidly invalidate such claims that violence from war has statistically experienced a decline. -->


# Probability and Statistical Inference: Frequentist and Bayesian






Ill posed inverse problems

  - Bernoulli *Ars Conjetandi* and INFERENCE (see page 7 of BF)
  - See main thesis on page 9 of BF

Definition of a Probability
  - classical answer (p 21, 25 of bf)
  - subjective interpretation (p 35 of bf; 44 of bf re dutch book)
  - frequency definition (p 27 fo bf)
  
Law of Large Numbers

Central Limit Theorem

When the logic starts to break down:

The Ludic Fallacy

Monty Hall Problem
Boy or Girl Paradox
Sally Clark and SIDS (Prosecutor's Fallacy?)
Base-Rate Neglect (Prosecutor's Fallacy?)

http://bactra.org/reviews/error/diagnostic-testing.html

Frequentism

Bayesianism

Mixed perspectives (informal)

"Turning the Bayesian Crank" and "Fixed Prior for excluded terms in an regression model"

Controlling Error Rates

Duhem-Quine and Methodological Underdetermination

Reproducibility Crisis



# P-values, Neyman-Pearson Testing, and the P-Value Fallacy

start with a metaphor, big complex machine with an output and multiple changing levers...

# S Values and Bayes Factors

# Confidence Intervals and Credible Intervals

# Statistical Consequences of "Heavy Tails"

# Takeaways

# Why Does This Matter?

\newpage

# References