# Site settings
title: IMCS
subtitle: Introduction to Monte Carlo Simulation
description: |
    <p>This course covers will serve as an introduction to Monte Carlo simulations in the quantitative sciences.</p>

    <p>By the end of this course you should have a solid understanding of:</p>
    <ul>
        <li>the role, scope, and purpose of Monte Carlo simulation</li>
        <li>when/why one should use Monte Carlo simulations</li>
        <li>the challenges and limitations of using Monte Carlo simulations</li>
        <li>how to design, deploy, and analyze Monte Carlo simulations in R</li>
    </ul>
    <br>
    <p>
    Their are several resources on how to design and analyze Monte Carlo simulation studies in the 
    quantitative sciences. This course consolidates and adds to these resources by instructing through a 
    specific example question. Simulation methods are extremely flexible, and can be used to understand 
    and evaluate methodology in a number of different ways. This is an applied course. By the end of the course, 
    students will be able to implement their own Monte Carlo simulation to estimate bias, mean squared error, 
    confidence interval coverage, and other statistics for an estimator of their choice.
    </p>

baseurl: "/IMCS" # the github directory
url: "https://ainaimi.github.io/" # the base hostname & protocol for your site

# host the syllabus on google docs
# File: Publish to Web
syllabus_url: #
githubdir: "ainaimi/IMCS"

# Author/user information
email: ashley.naimi@emory.edu
twitter_username: ashley_naimi
github_username:  ainaimi
authorurl: "https://bit.ly/3GFu2o1"
# address: |
#     Emory University
#     Department of Biostatistics and Bioinformatics
#     1518 Clifton Rd. NE
#     Atlanta, GA 30322

# Use collection to manage records
collections: 
    recordings:
        output: true
        permalink: /:collection/:name

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
