# Site settings
title: EPI560
subtitle: Epidemiologic Methods IV
description: |
    <p>This course is an intermediate PhD/MSPH course in the sequence of core courses in Epidemiology at Emory Unviersity.</p>

    <p>By the end of this course students should be able to:</p>
    <ul>
        <li>Integrate fundamental epidemiologic concepts related to disease occurrence and associations.</li>
        <li>Articulate fundamental concepts in the potential outcomes frameworks.</li>
        <li>Understand the relation between exchangeability and bias.</li>
        <li>Understand and articulate the differences between truncation and censoring.</li>
        <li>Understand and recognize when and how to use regression models in various epidemiologic settings.</li>
        <li>Recognize the presence, impact, and ways to analyse competing risk data.</li>
        <li>Understand bootstrap and its potential applications to the analysis of epidemiologic data.</li>
        <li>Correctly interpret p values and confidence intervals.</li>
    </ul>

baseurl: "/EPI560" # the github directory
url: "https://ainaimi.github.io/" # the base hostname & protocol for your site

# host the syllabus on google docs
# File: Publish to Web
syllabus_url: #
githubdir: "ainaimi/EPI560"

# Author/user information
email: ashley.naimi@emory.edu
twitter_username: ashley_naimi
github_username:  ainaimi
authorurl: "https://bit.ly/3GFu2o1"
# address: |
#     Emory University
#     Department of Biostatistics and Bioinformatics
#     1518 Clifton Rd. NE
#     Atlanta, GA 30322

# Use collection to manage records
collections: 
    recordings:
        output: true
        permalink: /:collection/:name

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
