---
title: "Probability and Statistical Inference: Frequentist and Bayesian Perspectives"
author: "Ashley I Naimi"
date: "`r paste0('Spring ', 2024)`" #format(Sys.Date(), '%Y')
urlcolor: blue
bibliography: ref.bib
link-citations: yes
output: 
    bookdown::pdf_book:
      base_format: tint::tintPdf
      toc: true
      number_sections: true
      includes:
        in_header: ../../misc/preamble.tex
      latex_engine: xelatex
    html_document:
      theme: readable
      toc: true
      toc_float: true
      number_sections: true
      css: ../../misc/style.css
---

```{r setup, include=FALSE}
library(knitr)
library(formatR)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)

packages <- c( "data.table","tidyverse","ggplot2","ggExtra","formatR",
               "gridExtra","skimr","here","RColorBrewer","survival")

for (package in packages) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package, repos='http://lib.stat.cmu.edu/R/CRAN')
  }
}

for (package in packages) {
  library(package, character.only=T)
}

remotes::install_github("rstudio/fontawesome")

library(fontawesome)

thm <- theme_classic() +
  theme(
    legend.position = "top",
    legend.background = element_rect(fill = "transparent", colour = NA),
    legend.key = element_rect(fill = "transparent", colour = NA)
  )
theme_set(thm)
```

\newpage
\onehalfspacing

<!-- *There is considerable uncertainty about the study of uncertainty* -->

this chapter should be about the ways we (can) manage "uncertainty", how we've implicitly adopted one (flawed and) fallacious way, what some other options are ... 

Augustus de Morgan (1838): I consider the word probability as meaning the state of mind with respect to an assertion, a coming event, or any other matter on which absolute knowledge does not exist. 

John Venn freq defn of prob...

# Probability versus Statistics (versus Machine Learning) as Fields of Study



Ill posed inverse problems

  - Bernoulli *Ars Conjetandi* and INFERENCE (see page 7 of BF)
  - See main thesis on page 9 of BF

Definition of a Probability
  - classical answer (p 21, 25 of bf)
  - subjective interpretation (p 35 of bf; 44 of bf re dutch book)
  - frequency definition (p 27 fo bf)
  
Law of Large Numbers

The Ludic Fallacy

Monty Hall Problem
Boy or Girl Paradox
Sally Clark and SIDS (Prosecutor's Fallacy?)
Base-Rate Neglect (Prosecutor's Fallacy?)

http://bactra.org/reviews/error/diagnostic-testing.html

Frequentism

Bayesianism

Mixed perspectives (informal)

"Turning the Bayesian Crank" and "Fixed Prior for excluded terms in an regression model"

Controlling Error Rates

Duhem-Quine and Methodological Underdetermination

Reproducibility Crisis



# Takeaways


# Why Does This Matter?

\newpage

# References